/* Clipboard-Flux isolated Footprint sheet manager -- 0.23.1.
   It never attaches to the canvas or existing Footprint controls. Each floor
   is a snapshot in footprintReferenceBlobs; switching projects that snapshot
   into the core app's existing footprint/reference fields, then reloads. */
(function(){
'use strict';
if(window.__clipboardFluxFootprintSheetManagerInstalled)return;
window.__clipboardFluxFootprintSheetManagerInstalled=true;
if(typeof indexedDB==='undefined'||typeof MutationObserver==='undefined')return;
var DB='clipboard-flux-photos',DATA='inspectionData',STORE='footprintReferenceBlobs',ACTIVE='clipboard-flux-active-inspection',RETURN='clipboard-flux-return-footprint-sheet';
var META='::fp-sheets-v2-meta',SHEET='::fp-sheets-v2::',OLDMETA='::footprint-sheets-meta',OLDSHEET='::footprint-sheet::',OLDREF='::footprint-sheet-reference::';
var serial=0;
function id(){try{return localStorage.getItem(ACTIVE)||'';}catch(e){return'';}}
function mk(i){return i+META;} function sk(i,s){return i+SHEET+s;} function omk(i){return i+OLDMETA;} function osk(i,s){return i+OLDSHEET+s;} function ork(i,s){return i+OLDREF+s;}
function now(){return new Date().toISOString();} function blank(){return{version:1,strokes:[]};} function sid(){return'sheet_'+Date.now()+'_'+Math.random().toString(36).slice(2,8);} function clone(v){return v==null?v:JSON.parse(JSON.stringify(v));}
function open(){return new Promise(function(ok,bad){var r;try{r=indexedDB.open(DB);}catch(e){bad(e);return;}r.onsuccess=function(){ok(r.result);};r.onerror=function(){bad(r.error||new Error('Storage open failed.'));};r.onblocked=function(){bad(new Error('Storage is blocked.'));};});}
function get(store,key){return open().then(function(db){return new Promise(function(ok,bad){if(!db.objectStoreNames.contains(store)){db.close();ok(null);return;}var tx=db.transaction(store,'readonly'),r=tx.objectStore(store).get(key);r.onsuccess=function(){var v=r.result||null;db.close();ok(v);};r.onerror=function(){var e=r.error;db.close();bad(e);};});});}
function put(store,rec){return open().then(function(db){return new Promise(function(ok,bad){var tx=db.transaction(store,'readwrite');tx.objectStore(store).put(rec);tx.oncomplete=function(){db.close();ok();};tx.onerror=function(){var e=tx.error;db.close();bad(e);};});});}
function del(store,key){return open().then(function(db){return new Promise(function(ok,bad){if(!db.objectStoreNames.contains(store)){db.close();ok();return;}var tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(key);tx.oncomplete=function(){db.close();ok();};tx.onerror=function(){var e=tx.error;db.close();bad(e);};});});}
function clean(n,f){n=String(n==null?'':n).trim().replace(/\s+/g,' ');return(n||f||'Footprint').slice(0,60);}
function def(n){return['1st Floor','2nd Floor','3rd Floor','Basement','Garage','ADU'][n]||('Sheet '+(n+1));}
function norm(raw,i){if(!raw||!Array.isArray(raw.sheets)||!raw.sheets.length)return null;var seen={},ss=raw.sheets.filter(function(s){return s&&s.id&&!seen[s.id]&&(seen[s.id]=1);}).map(function(s,n){return{id:s.id,name:clean(s.name,def(n)),order:n};});if(!ss.length)return null;var a=raw.activeSheetId;if(!ss.some(function(s){return s.id===a;}))a=ss[0].id;return{inspectionId:mk(i),kind:'footprintSheetsMetaV2',parentInspectionId:i,version:2,activeSheetId:a,sheets:ss,updatedAt:raw.updatedAt||now()};}
function readMeta(i){return get(STORE,mk(i)).then(function(r){return norm(r,i);});}
function writeMeta(m){m.updatedAt=now();m.sheets.forEach(function(s,n){s.order=n;});return put(STORE,m);}
function waitSave(){var start=Date.now();return new Promise(function(ok){function c(){var e=document.querySelector('.save-status'),t=e?String(e.textContent||'').toLowerCase():'';if(t.indexOf('saving')!==-1&&Date.now()-start<3500){setTimeout(c,120);return;}setTimeout(ok,Math.max(0,820-(Date.now()-start)));}c();});}
function activeSnap(i){return Promise.all([get(DATA,i),get(STORE,i)]).then(function(r){if(!r[0])throw new Error('Active inspection data is unavailable.');return{footprint:clone(r[0].footprint)||blank(),reference:clone(r[0].reference)||null,blob:r[1]&&r[1].blob?r[1].blob:null};});}
function rec(i,s,x){return{inspectionId:sk(i,s),kind:'footprintSheetV2',parentInspectionId:i,sheetId:s,footprint:clone(x&&x.footprint)||blank(),reference:clone(x&&x.reference)||null,blob:x&&x.blob?x.blob:null,updatedAt:now()};}
function snap(i,m){return activeSnap(i).then(function(x){return put(STORE,rec(i,m.activeSheetId,x));});}
function activate(i,r){if(!r)throw new Error('Footprint sheet data is unavailable.');var ref=clone(r.reference)||null;if(ref)ref.locked=true;return get(DATA,i).then(function(d){if(!d)throw new Error('Active inspection data is unavailable.');d=clone(d);d.inspectionId=i;d.footprint=clone(r.footprint)||blank();d.reference=ref;return put(DATA,d);}).then(function(){return r.blob?put(STORE,{inspectionId:i,blob:r.blob}):del(STORE,i);}).then(function(){if(r.reference&&r.reference.locked!==true){r.reference=ref;r.updatedAt=now();return put(STORE,r);}});}
function migrate(i){return get(DATA,omk(i)).then(function(old){if(!old||!Array.isArray(old.sheets)||!old.sheets.length)return null;var m=norm(old,i);return Promise.all(m.sheets.map(function(s){return Promise.all([get(DATA,osk(i,s.id)),get(STORE,ork(i,s.id))]).then(function(x){var d=x[0]||{},rr=x[1]||{};return put(STORE,rec(i,s.id,{footprint:d.footprint||blank(),reference:d.reference||null,blob:rr.blob||null})).then(function(){return Promise.all([del(DATA,osk(i,s.id)),del(STORE,ork(i,s.id))]);});});})).then(function(){return del(DATA,omk(i));}).then(function(){return writeMeta(m);}).then(function(){return m;});});}
function ensure(i){if(!i)return Promise.reject(new Error('No active inspection.'));return readMeta(i).then(function(m){if(m)return m;return migrate(i).then(function(mm){if(mm)return snap(i,mm).then(function(){return mm;});var s=sid(),fresh={inspectionId:mk(i),kind:'footprintSheetsMetaV2',parentInspectionId:i,version:2,activeSheetId:s,sheets:[{id:s,name:'1st Floor',order:0}],updatedAt:now()};return activeSnap(i).then(function(x){return put(STORE,rec(i,s,x));}).then(function(){return writeMeta(fresh);}).then(function(){return fresh;});});});}
function busy(t){var p=document.getElementById('clipboard-flux-footprint-sheets-v2');if(!p)return;p.classList.add('busy');Array.prototype.forEach.call(p.querySelectorAll('button,select'),function(e){e.disabled=true;});var s=p.querySelector('.fp-sheet-status');if(s)s.textContent=t||'Working…';}
function reload(){try{sessionStorage.setItem(RETURN,'1');}catch(e){}location.reload();}
function fail(prefix,e){if(console&&console.error)console.error('Clipboard-Flux:',prefix,e);window.alert(prefix+': '+e.message);render();}
function sw(i,target){busy('Saving current sheet…');ensure(i).then(function(m){if(target===m.activeSheetId){render();return;}return waitSave().then(function(){return snap(i,m);}).then(function(){return get(STORE,sk(i,target));}).then(function(r){return activate(i,r);}).then(function(){m.activeSheetId=target;return writeMeta(m);}).then(reload);}).catch(function(e){fail('Could not switch Footprint sheets',e);});}
function nextName(m,src){var a=['1st Floor','2nd Floor','3rd Floor','Basement','Garage','ADU'];for(var n=0;n<a.length;n++)if(!m.sheets.some(function(s){return s.name===a[n];}))return a[n];return clean(src,'Footprint')+' Copy';}
function add(i){ensure(i).then(function(m){var sug=nextName(m,def(m.sheets.length)),name=prompt('Name the new Footprint sheet:',sug);if(name===null)return;name=clean(name,sug);busy('Creating sheet…');return waitSave().then(function(){return snap(i,m);}).then(function(){var s=sid(),r=rec(i,s,{footprint:blank(),reference:null,blob:null});return put(STORE,r).then(function(){m.sheets.push({id:s,name:name,order:m.sheets.length});m.activeSheetId=s;return writeMeta(m).then(function(){return activate(i,r);});});}).then(reload);}).catch(function(e){fail('Could not create a Footprint sheet',e);});}
function dup(i){ensure(i).then(function(m){var sm=m.sheets.filter(function(s){return s.id===m.activeSheetId;})[0],sug=nextName(m,sm&&sm.name),name=prompt('Name the duplicated Footprint sheet:',sug);if(name===null)return;name=clean(name,sug);busy('Duplicating sheet…');return waitSave().then(function(){return snap(i,m);}).then(function(){return get(STORE,sk(i,m.activeSheetId));}).then(function(src){if(!src)throw new Error('Current sheet could not be found.');var s=sid(),ref=clone(src.reference)||null;if(ref)ref.locked=true;var r=rec(i,s,{footprint:src.footprint,reference:ref,blob:src.blob||null});return put(STORE,r).then(function(){m.sheets.push({id:s,name:name,order:m.sheets.length});m.activeSheetId=s;return writeMeta(m).then(function(){return activate(i,r);});});}).then(reload);}).catch(function(e){fail('Could not duplicate the Footprint sheet',e);});}
function rename(i){ensure(i).then(function(m){var s=m.sheets.filter(function(x){return x.id===m.activeSheetId;})[0];if(!s)return;var n=prompt('Rename Footprint sheet:',s.name);if(n===null)return;s.name=clean(n,s.name);return writeMeta(m).then(render);}).catch(function(e){fail('Could not rename the Footprint sheet',e);});}
function remove(i){ensure(i).then(function(m){if(m.sheets.length<2){alert('At least one Footprint sheet is required.');return;}var n=m.sheets.findIndex(function(s){return s.id===m.activeSheetId;}),cur=m.sheets[n],target=m.sheets[n>0?n-1:1];if(!confirm('Delete “'+cur.name+'”? Its drawing and reference sketch will be removed.'))return;busy('Deleting sheet…');return Promise.all([del(STORE,sk(i,cur.id)),get(STORE,sk(i,target.id))]).then(function(x){if(!x[1])throw new Error('Next sheet could not be found.');m.sheets.splice(n,1);m.activeSheetId=target.id;return activate(i,x[1]).then(function(){return writeMeta(m);});}).then(reload);}).catch(function(e){fail('Could not delete the Footprint sheet',e);});}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function css(){if(document.getElementById('clipboard-flux-footprint-sheets-v2-style'))return;var s=document.createElement('style');s.id='clipboard-flux-footprint-sheets-v2-style';s.textContent='#clipboard-flux-footprint-sheets-v2{background:#fff;border:1px solid var(--line,#d9e0e6);border-radius:12px;padding:9px 10px;margin-bottom:10px}.fp-sheet-label{font-size:11.5px;font-weight:800;color:var(--muted,#66727e);text-transform:uppercase;letter-spacing:.04em;margin-bottom:6px}.fp-sheet-row{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.fp-sheet-select{flex:1 1 160px;min-width:0;min-height:44px;border:1.5px solid var(--navy,#17324d);border-radius:10px;background:#fff;color:var(--navy,#17324d);padding:0 10px;font:700 14px system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif}.fp-sheet-btn{min-height:44px;border:1.5px solid var(--navy,#17324d);border-radius:10px;background:#fff;color:var(--navy,#17324d);padding:0 11px;font-size:13px;font-weight:800}.fp-sheet-btn.primary{background:var(--navy,#17324d);color:#fff}.fp-sheet-btn.danger{border-color:#a33;color:#a33}.fp-sheet-status{font-size:11.5px;color:var(--muted,#66727e);min-height:14px;margin-top:5px}#clipboard-flux-footprint-sheets-v2.busy{opacity:.76}@media(max-width:430px){.fp-sheet-select{flex-basis:100%}.fp-sheet-btn{flex:1 1 auto;padding:0 8px}}';document.head.appendChild(s);}
function html(m){var o=m.sheets.map(function(s){return'<option value="'+esc(s.id)+'"'+(s.id===m.activeSheetId?' selected':'')+'>'+esc(s.name)+'</option>';}).join('');return'<div class="fp-sheet-label">Footprint Sheets</div><div class="fp-sheet-row"><select class="fp-sheet-select" aria-label="Footprint sheet">'+o+'</select><button type="button" class="fp-sheet-btn primary" data-fps="new">+ New</button><button type="button" class="fp-sheet-btn" data-fps="dup">Duplicate</button><button type="button" class="fp-sheet-btn" data-fps="rename">Rename</button><button type="button" class="fp-sheet-btn danger" data-fps="delete"'+(m.sheets.length<2?' disabled':'')+'>Delete</button></div><div class="fp-sheet-status"></div>';}
function render(){var c=document.getElementById('footprint-canvas'),i=id();if(!c||!i)return Promise.resolve();var token=++serial;css();return ensure(i).then(function(m){if(token!==serial||!document.getElementById('footprint-canvas'))return;var p=document.getElementById('clipboard-flux-footprint-sheets-v2');if(!p){p=document.createElement('div');p.id='clipboard-flux-footprint-sheets-v2';var t=document.querySelector('.footprint-toolbar');(t&&t.parentNode?t.parentNode:c.parentNode).insertBefore(p,t||c);}p.innerHTML=html(m);var q=p.querySelector('.fp-sheet-select');q.addEventListener('change',function(){sw(i,q.value);});Array.prototype.forEach.call(p.querySelectorAll('[data-fps]'),function(b){b.addEventListener('click',function(){var a=b.getAttribute('data-fps');if(a==='new')add(i);else if(a==='dup')dup(i);else if(a==='rename')rename(i);else remove(i);});});}).catch(function(e){if(console&&console.error)console.error('Clipboard-Flux: sheet panel failed',e);});}
function resume(){var yes=false;try{yes=sessionStorage.getItem(RETURN)==='1';}catch(e){}if(!yes)return;var n=0,t=setInterval(function(){n++;var bs=document.querySelectorAll('#tabs button');for(var j=0;j<bs.length;j++)if(String(bs[j].textContent||'').trim().replace(/\s+/g,' ')==='Footprint'){clearInterval(t);try{sessionStorage.removeItem(RETURN);}catch(e){}bs[j].click();return;}if(n>80){clearInterval(t);try{sessionStorage.removeItem(RETURN);}catch(e){}}},100);}
function cleanup(i){return Promise.all([readMeta(i),get(DATA,omk(i))]).then(function(ms){var jobs=[],m=ms[0],old=ms[1];if(m){jobs.push(del(STORE,mk(i)));m.sheets.forEach(function(x){jobs.push(del(STORE,sk(i,x.id)));});}if(old&&Array.isArray(old.sheets)){jobs.push(del(DATA,omk(i)));old.sheets.forEach(function(x){if(x&&x.id){jobs.push(del(DATA,osk(i,x.id)));jobs.push(del(STORE,ork(i,x.id)));}});}return Promise.all(jobs);});}
function emptyFp(d){var f=d&&d.footprint,s=f&&Array.isArray(f.strokes)?f.strokes:[];return s.length===0&&!(d&&d.reference);}
document.addEventListener('click',function(ev){var b=ev.target&&ev.target.closest?ev.target.closest('[data-role="insp-reset"]'):null;if(!b)return;var i=id();if(!i)return;get(DATA,i).then(function(before){if(!before)return;var bj='';try{bj=JSON.stringify(before);}catch(e){}var start=Date.now();function poll(){get(DATA,i).then(function(after){var aj='';try{aj=JSON.stringify(after);}catch(e){}if(after&&aj!==bj&&emptyFp(after)){cleanup(i).catch(function(){});return;}if(Date.now()-start<3000)setTimeout(poll,180);}).catch(function(){});}setTimeout(poll,180);}).catch(function(){});},true);
var obs=new MutationObserver(function(rs){var found=false;rs.forEach(function(r){Array.prototype.forEach.call(r.addedNodes||[],function(n){if(n&&n.nodeType===1&&(n.id==='footprint-canvas'||(n.querySelector&&n.querySelector('#footprint-canvas'))))found=true;});});if(found)setTimeout(render,0);});
obs.observe(document.documentElement,{childList:true,subtree:true});if(document.getElementById('footprint-canvas'))render();resume();
})();
