/* Clipboard-Flux multi-sheet Footprint print bridge -- 0.23.1
   Print-only companion: never touches the live canvas/tool state. */
(function(){
'use strict';
if(window.__clipboardFluxFootprintSheetsPrintInstalled)return;window.__clipboardFluxFootprintSheetsPrintInstalled=true;
if(typeof indexedDB==='undefined'||typeof MutationObserver==='undefined')return;
var DB='clipboard-flux-photos',DATA='inspectionData',STORE='footprintReferenceBlobs',ACTIVE='clipboard-flux-active-inspection',META='::fp-sheets-v2-meta',SHEET='::fp-sheets-v2::',EDGE=1600,PAD=.08,WIDTH={thin:2.5,medium:4.5,thick:7.5},TIMEOUT=4500;
function sk(i,s){return i+SHEET+s;}function finite(v,f){return typeof v==='number'&&isFinite(v)?v:f;}
function iid(doc){var f=doc&&doc.querySelector&&doc.querySelector('.pdf-footer-note'),t=f?String(f.textContent||''):'',a=t.lastIndexOf('ID:');if(a!==-1){var x=t.slice(a+3).trim();if(x)return x;}try{return localStorage.getItem(ACTIVE)||'';}catch(e){return'';}}
function open(){return new Promise(function(ok,bad){var r;try{r=indexedDB.open(DB);}catch(e){bad(e);return;}r.onsuccess=function(){ok(r.result);};r.onerror=function(){bad(r.error||new Error('Could not open inspection storage.'));};r.onblocked=function(){bad(new Error('Inspection storage is blocked.'));};});}
function load(i){return open().then(function(db){return new Promise(function(ok,bad){if(!db.objectStoreNames.contains(DATA)||!db.objectStoreNames.contains(STORE)){db.close();ok(null);return;}var tx=db.transaction([DATA,STORE],'readonly'),ds=tx.objectStore(DATA),ss=tx.objectStore(STORE),mr=ss.get(i+META),dr=ds.get(i),br=ss.get(i),meta=null,data=null,blob=null,reqs=[];mr.onsuccess=function(){meta=mr.result||null;if(!meta||!Array.isArray(meta.sheets)||!meta.sheets.length)return;meta.sheets.forEach(function(s){if(s&&s.id)reqs.push({sheet:s,req:ss.get(sk(i,s.id))});});};dr.onsuccess=function(){data=dr.result||null;};br.onsuccess=function(){blob=br.result&&br.result.blob?br.result.blob:null;};tx.oncomplete=function(){var out=null;if(meta&&Array.isArray(meta.sheets)&&meta.sheets.length)out={meta:meta,activeData:data,activeBlob:blob,records:reqs.map(function(x){return{sheet:x.sheet,record:x.req.result||null};})};db.close();ok(out);};tx.onerror=function(){var e=tx.error||new Error('Could not read Footprint sheets.');db.close();bad(e);};});});}
function pts(s){if(!s||typeof s!=='object')return[];if(s.type==='line'&&s.a&&s.b)return[s.a,s.b];if(s.type==='freehand'&&Array.isArray(s.points))return s.points;return[];}
function add(b,x,y){if(!isFinite(x)||!isFinite(y))return;b.minX=Math.min(b.minX,x);b.maxX=Math.max(b.maxX,x);b.minY=Math.min(b.minY,y);b.maxY=Math.max(b.maxY,y);}
function geom(r,has){if(!has||!r||r.visible===false)return null;var w=finite(r.width,0),h=finite(r.height,0);if(w<=0||h<=0)return null;var t=r.transform||{},s=finite(t.scale,1);if(s<=0)s=1;return{cx:finite(t.x,0),cy:finite(t.y,0),width:w*s,height:h*s,rotation:finite(t.rotation,0),opacity:Math.max(.05,Math.min(1,finite(r.opacity,.55)))};}
function bounds(strokes,g){var b={minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity};(strokes||[]).forEach(function(s){pts(s).forEach(function(p){if(p)add(b,Number(p.x),Number(p.y));});});if(g){var hw=g.width/2,hh=g.height/2,c=Math.cos(g.rotation),sn=Math.sin(g.rotation);[[-hw,-hh],[hw,-hh],[hw,hh],[-hw,hh]].forEach(function(p){add(b,g.cx+p[0]*c-p[1]*sn,g.cy+p[0]*sn+p[1]*c);});}return isFinite(b.minX)?b:null;}
function stroke(ctx,s){var p=pts(s);if(p.length<2)return;ctx.lineWidth=WIDTH[s.width]||WIDTH.medium;ctx.beginPath();ctx.moveTo(Number(p[0].x),Number(p[0].y));for(var n=1;n<p.length;n++)ctx.lineTo(Number(p[n].x),Number(p[n].y));ctx.stroke();}
function decode(blob){if(!blob)return Promise.resolve(null);if(typeof createImageBitmap==='function')return createImageBitmap(blob).then(function(b){return{image:b,close:function(){try{b.close();}catch(e){}}};});return new Promise(function(ok,bad){var u=URL.createObjectURL(blob),img=new Image();img.onload=function(){ok({image:img,close:function(){URL.revokeObjectURL(u);}});};img.onerror=function(){URL.revokeObjectURL(u);bad(new Error('Could not decode reference sketch.'));};img.src=u;});}
function render(r){if(!r)return Promise.resolve(null);var fp=r.footprint||{},strokes=Array.isArray(fp.strokes)?fp.strokes:[],blob=r.blob||null,g=geom(r.reference,!!blob),b=bounds(strokes,g);if(!b)return Promise.resolve(null);return decode(blob).catch(function(){return null;}).then(function(d){var w=b.maxX-b.minX,h=b.maxY-b.minY,long=Math.max(w,h,1),pad=Math.max(long*PAD,10),tw=w+pad*2,th=h+pad*2,scale=EDGE/Math.max(tw,th,1),c=document.createElement('canvas');c.width=Math.max(1,Math.round(tw*scale));c.height=Math.max(1,Math.round(th*scale));var ctx=c.getContext('2d');if(!ctx){if(d)d.close();return null;}ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.translate((pad-b.minX)*scale,(pad-b.minY)*scale);ctx.scale(scale,scale);if(g&&d&&d.image){ctx.save();ctx.globalAlpha=g.opacity;ctx.translate(g.cx,g.cy);ctx.rotate(g.rotation);ctx.drawImage(d.image,-g.width/2,-g.height/2,g.width,g.height);ctx.restore();}ctx.lineCap='round';ctx.lineJoin='round';ctx.strokeStyle='#1c3a52';strokes.forEach(function(s){stroke(ctx,s);});if(d)d.close();return c.toDataURL('image/png');});}
function record(saved,sid){var f=null;saved.records.some(function(x){if(x.sheet.id===sid){f=x;return true;}return false;});if(!f)return null;var r=f.record||{};if(sid===saved.meta.activeSheetId&&saved.activeData)return{footprint:saved.activeData.footprint||{version:1,strokes:[]},reference:saved.activeData.reference||null,blob:saved.activeBlob||null};return{footprint:r.footprint||{version:1,strokes:[]},reference:r.reference||null,blob:r.blob||null};}
function wait(img){if(!img)return Promise.resolve();if(img.complete)return img.decode?img.decode().catch(function(){}):Promise.resolve();return new Promise(function(ok){var d=function(){ok();};img.addEventListener('load',d,{once:true});img.addEventListener('error',d,{once:true});});}
function install(doc,items){if(!doc||!doc.body||!items.length)return Promise.resolve();var old=doc.querySelectorAll('.pdf-footprint-section'),anchor=old.length?old[0]:(doc.querySelector('.pdf-notes-section')||doc.querySelector('.pdf-footer-note')),parent=anchor&&anchor.parentNode?anchor.parentNode:doc.body,before=anchor||null;Array.prototype.forEach.call(old,function(x){if(x.parentNode)x.parentNode.removeChild(x);});var waits=[];items.forEach(function(item,n){var sec=doc.createElement('div');sec.className='pdf-section pdf-footprint-section';if(n>0){sec.style.breakBefore='page';sec.style.pageBreakBefore='always';}var h=doc.createElement('div');h.className='pdf-section-heading';h.textContent='FOOTPRINT — '+item.name;var img=doc.createElement('img');img.className='pdf-footprint-image';img.alt='';img.src=item.url;sec.appendChild(h);sec.appendChild(img);parent.insertBefore(sec,before);waits.push(wait(img));});var empty=doc.querySelector('.pdf-empty-note');if(empty&&empty.parentNode)empty.parentNode.removeChild(empty);return Promise.all(waits).then(function(){});}
function enrich(doc){var i=iid(doc);if(!i)return Promise.resolve();return load(i).then(function(s){if(!s)return;return Promise.all(s.meta.sheets.map(function(sh){return render(record(s,sh.id)).then(function(url){return url?{name:String(sh.name||'Footprint'),url:url}:null;});})).then(function(xs){return install(doc,xs.filter(Boolean));});});}
function bounded(p){return new Promise(function(ok){var done=false,t=setTimeout(function(){if(!done){done=true;ok();}},TIMEOUT);p.then(function(){if(!done){done=true;clearTimeout(t);ok();}},function(e){if(!done){done=true;clearTimeout(t);if(window.console&&console.warn)console.warn('Clipboard-Flux: multi-sheet Footprint print failed',e);ok();}});});}
function hook(frame){if(!frame||frame.tagName!=='IFRAME'||!Object.prototype.hasOwnProperty.call(frame,'__objectUrls'))return;function wrap(){var w=frame.contentWindow,d=w&&w.document;if(!w||!d||typeof w.print!=='function')return false;var down=w.print;if(down.__clipboardFluxSheetsPrintWrapper)return true;var fn=function(){if(frame.__clipboardFluxSheetsPrintBusy)return;frame.__clipboardFluxSheetsPrintBusy=true;bounded(enrich(d)).then(function(){frame.__clipboardFluxSheetsPrintBusy=false;down.call(w);});};fn.__clipboardFluxSheetsPrintWrapper=true;try{w.print=fn;}catch(e){try{Object.defineProperty(w,'print',{configurable:true,writable:true,value:fn});}catch(ignore){}}return w.print===fn;}if(!frame.__clipboardFluxSheetsPrintLoad){frame.__clipboardFluxSheetsPrintLoad=true;frame.addEventListener('load',wrap,true);}wrap();}
var ob=new MutationObserver(function(rs){rs.forEach(function(r){Array.prototype.forEach.call(r.addedNodes||[],function(n){if(!n||n.nodeType!==1)return;if(n.tagName==='IFRAME')hook(n);if(n.querySelectorAll)Array.prototype.forEach.call(n.querySelectorAll('iframe'),hook);});});});ob.observe(document.documentElement,{childList:true,subtree:true});Array.prototype.forEach.call(document.querySelectorAll('iframe'),hook);
})();
